baseURL = 'http://scot.baltig-pages.sandia.gov/scot4/scot4-docs/'
languageCode = 'en-us'
title = 'Sandia Cyber Omni Tracker'
theme = 'hugo-theme-relearn'
canonifyURLS = true
[params]
    themeVariant = ['zen-dark', 'zen-light']
